// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBGkZfaaIk2Ac948FcwVZOq8V2gM_n27Q',
    appId: '1:232119674856:web:e747845a4eaf609322e65d',
    messagingSenderId: '232119674856',
    projectId: 'attendme-98fbe',
    authDomain: 'attendme-98fbe.firebaseapp.com',
    storageBucket: 'attendme-98fbe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB91EWyKlPMbwVwMIceLrFBwZwNJ9wzUZs',
    appId: '1:232119674856:android:60a4d74bf670a5c022e65d',
    messagingSenderId: '232119674856',
    projectId: 'attendme-98fbe',
    storageBucket: 'attendme-98fbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTwHddEdtER2bdKtpwuFWuGUQxK2BI31g',
    appId: '1:232119674856:ios:802835fd38c30e6d22e65d',
    messagingSenderId: '232119674856',
    projectId: 'attendme-98fbe',
    storageBucket: 'attendme-98fbe.appspot.com',
    iosClientId: '232119674856-lq6m62tuko9g0um1a0vqed1a7g9fpqgj.apps.googleusercontent.com',
    iosBundleId: 'attendme.app',
  );
}
